### ISSUE TITLE
Mentor list is out of date

### ISSUE THREAD

**Issue by jackfrys** [hacks/mentors#27]
I'm happy to be the change and add myself, but others of the current upperclass students should do the same.

Also, should we add new mentors at the top or bottom?

**Comment by aceyoung9** [comment]
Yo; alum who made the thing here.

What if we wipe the whole thing, then put in a new call for for submissions on the fb group?

**Comment by aceyoung9** [comment]
Closed via #28 ; Mentorship is cancelled \s
